"""initial schema

Revision ID: fcd865a7cc83
Revises: 
Create Date: 2026-05-08 10:26:29.208752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd865a7cc83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'review_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_contents_client_id'), 'contents', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_client_id'), table_name='contents')
    op.alter_column('contents', 'review_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###
